name: Check and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Get package.json version
      id: get_version
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Get latest release version
      id: get_release
      run: |
        curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' > latest_release.txt

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "$(cat latest_release.txt)" != "$PACKAGE_VERSION" ]; then
          echo "Version mismatch"
          echo "create_release=true" >> $GITHUB_ENV
        else
          echo "Version matches"
          echo "create_release=false" >> $GITHUB_ENV
        fi

    - name: Create new release
      if: env.create_release == 'true'
      run: |
        CURRENT_DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d  %H:%M')
        sed -i "s/\\$PACKAGE_VERSION/$PACKAGE_VERSION/g" CHANGELOG.md
        sed -i "s/\\$CURRENT_DATE/$CURRENT_DATE/g" CHANGELOG.md

        GENERATED_NOTES_BODY=$(gh api \
          --method POST \
          /repos/${{ github.repository }}/releases/generate-notes \
          -f tag_name="$PACKAGE_VERSION" \
          | jq -r .body)

        {
          echo "$GENERATED_NOTES_BODY"
          echo
          cat CHANGELOG.md
          echo
          echo "---"
          echo
          echo "使用方法:  "
          echo "- **Chrome / Edge / Arc / Brave:** [Chrome Web Store](https://chromewebstore.google.com/detail/fbgblmjbeebanackldpbmpacppflgmlj)"
          echo "- **国内用户:** [Crx 商店](https://www.crxsoso.com/webstore/detail/fbgblmjbeebanackldpbmpacppflgmlj)"
          echo "- **Firefox:** [Firefox Addons](https://addons.mozilla.org/zh-CN/firefox/addon/linux_do-scripts/)"
          echo
          echo "发布于：$CURRENT_DATE"
        } > release_body.md

        gh release create "$PACKAGE_VERSION" \
        -F release_body.md \
        -t "$PACKAGE_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}